name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # 安装 rsync
      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Run build script
        run: sh ./build.sh

      - name: Check for changes
        run: |
          git status
          git add .
          git diff --cached
          git commit --allow-empty -m "Update files" || echo "No changes to commit"

      - name: Push to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: .
          destination-github-username: 'amclubs'
          destination-repository-name: 'am-cf-linklet'
          user-email: ansoncloud8@gmail.com
          target-branch: main
