name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2

      # 安装 rsync
      - name: Install rsync
        run: apt-get update && apt-get install -y rsync

      - name: creates output
        run: sh ./build.sh  # some command from your repository that creates
                            # output to "source-directory" ("output" in the example)

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: .
          destination-github-username: 'amclubs'
          destination-repository-name: 'am-cf-linklet'
          user-email: ansoncloud8@gmail.com
          target-branch: main
