name: Repository Sync

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [ sync_repos ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Target Repository
      uses: actions/checkout@v3
      with:
        repository: ansoncloud8/am-cf-linklet
        ref: main
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Setup Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github@github.actions"

    - name: Sync Changes
      run: |
        git fetch --all
        git reset --hard origin/main
        git pull origin main

    - name: Push Changes to Target Repository
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
